### PR TITLE
Swedish: Update InfoPlist.strings

### PR DESCRIPTION
**Pull request by ATholin**

### CODE REVIEW

**Comment by Ziph0n** [comment]
Thank you!

**Comment by ATholin** [comment]
No problem!

<https://www.avast.com/sig-email?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail>
Virusfritt.
www.avast.com
<https://www.avast.com/sig-email?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail>
<#DAB4FAD8-2DD7-40BB-A1B8-4E2AA1F9FDF2>

2018-03-05 20:23 GMT+01:00 Ziph0n <notifications@github.com>:

**Comment by Ziph0n** [comment]
Hey! How can I contact you (email, twitter,...) A promo code is waiting for you :)

**Comment by ATholin** [comment]
Oh right! @ATholin on twitter is fine! :)

lör 17 mars 2018 kl. 17:25 skrev Ziph0n <notifications@github.com>:

**Comment by ATholin** [comment]
Sorry, I mean @AolinTholoni

lör 17 mars 2018 kl. 17:49 skrev Alexander Andersson Tholin <
alexander.a.tholin@gmail.com>:

**Comment by Ziph0n** [comment]
Thank you! I'll message you later

**Pull request merged**
